server:
  port:8080

---
spring:
  profiles:
    default: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysql
    url: jdbc:mysql://localhost:3306/Spring_boot
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"