server:
  port:8080

spring:
  profiles:
    active: dev
---

spring:
  profiles:
    default: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysql
    url: jdbc:mysql://localhost:3306/Spring_boot
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

---
spring:
  profiles:
    default: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysql
    url: jdbc:mysql://localhost:3306/Spring_boot-prod
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'