server:
  port: 8082

spring:
  datasource:
    username: mysql
    url: jdbc:mysql://localhost:3306/schooldb
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true